# Generated by Django 5.1.15 on 2026-06-29 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('qte_litres', models.FloatField(verbose_name='quantité (L)')),
                ('index_precedent', models.FloatField(default=0, verbose_name='index précédent')),
                ('index_actuel', models.FloatField(default=0, verbose_name='index actuel')),
                ('difference', models.FloatField(default=0, verbose_name="différence d'index")),
                ('client_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appros', to='fleet.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appros', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'approvisionnement',
                'verbose_name_plural': 'approvisionnements',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['driver', 'date'], name='fleet_appro_driver__34d13c_idx'), models.Index(fields=['vehicle', 'date'], name='fleet_appro_vehicle_a9a140_idx')],
            },
        ),
    ]
