# Generated by Django 5.1.15 on 2026-06-29 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_appro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'chauffeur / opérateur', 'verbose_name_plural': 'chauffeurs / opérateurs'},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='current_driver',
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='fleet.vehicle', verbose_name='camion assigné'),
        ),
    ]
