# Generated by Django 5.1.15 on 2026-07-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_driver_options_remove_vehicle_current_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='role',
            field=models.CharField(choices=[('driver', 'Chauffeur / opérateur'), ('supervisor', 'Superviseur (admin app)')], default='driver', max_length=16, verbose_name='rôle'),
        ),
    ]
