# Generated by Django 5.1.15 on 2026-07-02 13:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_driver_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('kind', models.CharField(choices=[('base', 'Base vie'), ('station', 'Station carburant'), ('chantier', 'Chantier'), ('autre', 'Autre')], default='chantier', max_length=16, verbose_name='type')),
                ('center', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='centre')),
                ('radius_m', models.FloatField(default=300, verbose_name='rayon (m)')),
                ('active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'zone',
                'verbose_name_plural': 'zones',
            },
        ),
        migrations.AlterField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('off_route', 'Sortie de couloir'), ('speeding', 'Excès de vitesse')], default='off_route', max_length=32),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('zone_enter', 'Arrivée en zone'), ('zone_exit', 'Départ de zone'), ('stop', 'Arrêt prolongé')], max_length=16)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(verbose_name='début')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='fleet.driver')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='fleet.position')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='fleet.vehicle')),
                ('geofence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='fleet.geofence')),
            ],
            options={
                'verbose_name': 'événement',
                'verbose_name_plural': 'événements',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['driver', 'started_at'], name='fleet_event_driver__fbda07_idx'), models.Index(fields=['kind', 'started_at'], name='fleet_event_kind_b1c0ac_idx')],
            },
        ),
    ]
