# Generated by Django 5.1.15 on 2026-07-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_geofence_alter_alert_kind_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('zone_enter', 'Arrivée en zone'), ('zone_exit', 'Départ de zone'), ('stop', 'Arrêt prolongé'), ('trip', 'Trajet')], max_length=16),
        ),
    ]
