# Generated by Django 5.1.15 on 2026-07-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_alter_event_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('off_route', 'Sortie de couloir'), ('speeding', 'Excès de vitesse'), ('red_zone', 'Entrée en zone rouge')], default='off_route', max_length=32),
        ),
        migrations.AlterField(
            model_name='geofence',
            name='kind',
            field=models.CharField(choices=[('base', 'Base vie'), ('station', 'Station carburant'), ('chantier', 'Chantier'), ('rouge', 'Zone rouge (interdite)'), ('autre', 'Autre')], default='chantier', max_length=16, verbose_name='type'),
        ),
    ]
