# Generated by Django 5.1.15 on 2026-07-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_alter_alert_kind_alter_geofence_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('off_route', 'Sortie de couloir'), ('speeding', 'Excès de vitesse'), ('red_zone', 'Entrée en zone rouge'), ('silence', 'Silence GPS')], default='off_route', max_length=32),
        ),
    ]
