# Generated by Codex on 2026-07-04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0008_alter_alert_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="Intervention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en_route", "En route"),
                            ("arrived", "Arrivé"),
                            ("done", "Terminé"),
                        ],
                        default="en_route",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to="fleet.event",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to="fleet.driver",
                    ),
                ),
            ],
            options={
                "verbose_name": "intervention",
                "verbose_name_plural": "interventions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="intervention",
            index=models.Index(fields=["event", "status"], name="fleet_inter_event_i_3a6f0c_idx"),
        ),
        migrations.AddIndex(
            model_name="intervention",
            index=models.Index(
                fields=["supervisor", "started_at"],
                name="fleet_inter_supervi_5b2a3e_idx",
            ),
        ),
    ]
