# Generated by Codex on 2026-07-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0009_intervention"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="emergency_phone",
            field=models.CharField(blank=True, max_length=32, verbose_name="contact urgence"),
        ),
        migrations.AddField(
            model_name="driver",
            name="whatsapp_phone",
            field=models.CharField(blank=True, max_length=32, verbose_name="WhatsApp"),
        ),
    ]
