# Generated by Codex on 2026-07-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0010_driver_contact_numbers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intervention",
            name="status",
            field=models.CharField(
                choices=[
                    ("en_route", "En route"),
                    ("arrived", "Arrivé"),
                    ("done", "Réglé"),
                    ("canceled", "Annulé"),
                ],
                default="en_route",
                max_length=16,
            ),
        ),
    ]
